// space-manual-topics — FEATURE_221 (SDK 0.7.47 dev tree) selfManual injection.
//
// 当用户在 Space 里问 "怎么开 popout / 怎么配 provider / 怎么粘图" 等"如何使用本工具"
// 的问题时,LLM 会调 SDK 自带的 kodax_manual tool。默认 manual 讲的是 KodaX SDK/REPL
// (npm install / .kodax/config 等),跟用户在 Space 里看到的 UI 完全对不上。
//
// 这里注入 Space 自己的产品手册:
//   - override 同 id 的 base topic → 答案换成 Space 的形态描述 (Settings modal / Sidebar /
//     右侧 popout / Cmd+Shift+P 命令面板 / 拖排项目 / 拖宽侧栏 / Ctrl+wheel 缩放 等)
//   - 新增 Space 独有 id (popouts / image-paste / smart-popout-director / zoom /
//     sidebar-resize / keyboard-shortcuts)
//   - aliases 同时挂 EN + 中文 — 用户用任一语言问都能命中
//
// 内容来源: README "当前能做什么" 列表 + docs/USAGE 主要功能 + docs/features/ 各 feature
// 设计文档。Body 控制在 ~500B 内 (SDK 4KB cap 之内,留余量给 reasoning)。
//
// 注: KodaX SDK 内核细节 (Auto Mode 工作机制 / Provider resilience / Skill registry
// 内部 etc) 不在这里 override —— 让 LLM 走 KodaX base topic 回答更准。Space 只 override
// 用户在 UI 里能直接看到/操作的形态。

import type { KodaXManualTopicInput } from '@kodax-ai/kodax/coding';

export const SPACE_PRODUCT_NAME = 'KodaX-Space';

export const SPACE_MANUAL_TOPICS: readonly KodaXManualTopicInput[] = [
  {
    id: 'overview',
    title: 'KodaX Space overview',
    summary: 'KodaX Space 是 KodaX 生态的 Electron 桌面客户端 (provider 中立 / 本地优先).',
    body: [
      'KodaX Space 是基于 Electron + React + TypeScript 构建的桌面 AI agent 客户端,',
      '复用 KodaX SDK 内核 (in-process import,无 sidecar).',
      '',
      '形态对标 Anthropic Claude Desktop 中的 Claude Code: 左侧栏管项目+session,中间',
      '是对话区 (流式 token + 工具卡片),右侧可弹出 Plan / Diff / Tasks / Terminal /',
      'Preview / MCP 等 popout 面板.',
      '',
      '关键特性: 12+ LLM provider 自由切换 / 真 PTY 多 tab 终端 / 图片粘贴多模态 /',
      'Smart popout director / 拖排项目 / 拖宽侧栏 / Ctrl+wheel 缩放 / Cmd+Shift+P',
      '命令面板 / 权限弹窗每工具确认.',
    ].join('\n'),
    aliases: ['Space', 'KodaX Space', 'KodaX-Space', '桌面端', '客户端', '桌面客户端'],
    nextTopics: ['quickstart', 'providers', 'popouts', 'sessions'],
  },
  {
    id: 'install',
    title: 'Install KodaX Space',
    summary: '从 GitHub Releases 下载 OS 对应的 installer (Win .exe / macOS .dmg / Linux AppImage).',
    body: [
      'KodaX Space 不发 npm package —— 它是个 Electron 桌面应用.',
      '',
      '下载: github.com/icetomoyo/KodaX-Space/releases 选最新 tag.',
      '  - Windows: KodaX-Space-Setup-x.y.z.exe (NSIS installer)',
      '  - macOS:   KodaX-Space-x.y.z.dmg (universal: Intel + Apple Silicon)',
      '  - Linux:   KodaX-Space-x.y.z.AppImage 或 .deb',
      '',
      '首启 SmartScreen / Gatekeeper 警告: installer 未签名 (项目定位"自家+可信用户",',
      '不走公开 Beta),手动点 Open / "仍要运行" 接受即可.',
      '',
      '源码开发: git clone + npm install + npm run dev (vite HMR + esbuild watch).',
    ].join('\n'),
    aliases: ['下载', '安装', '安装包', 'installer', 'setup', '怎么装', '怎么下载'],
    nextTopics: ['quickstart', 'providers'],
  },
  {
    id: 'quickstart',
    title: 'Quickstart',
    summary: '装好 → 配 provider key → 选项目目录 → New session → 开始对话.',
    body: [
      '第一次启动 KodaX Space 的 5 步:',
      '',
      '1. 点右上齿轮 ⚙ → Providers tab → 选一个 LLM provider (Anthropic / OpenAI /',
      '   Z.ai / OpenRouter / Ollama 等 13 内建,或加 custom) → 填 API key → Save.',
      '2. 左侧栏点 "+ Add project" → 选本地代码目录 (Space 用它当 session 的 cwd).',
      '3. 项目 row 上点 "+ New session" 创建新对话 session.',
      '4. 底部输入框打字 → Enter 发送,会看到流式 token + 工具卡片 (read/write/edit/',
      '   bash 等) 在中间面板逐条出现.',
      '5. 第一次出现 plan / diff / task 信号时右侧 popout 自动展开 (smart popout',
      '   director),Preferences 里可关.',
      '',
      '⌘K / Ctrl+K Quick Ask 临时问一次性问题, ⌘Shift+P / Ctrl+Shift+P 命令面板搜全部操作.',
    ].join('\n'),
    aliases: ['快速开始', '入门', '上手', '怎么用', 'getting started', 'how to start'],
    nextTopics: ['providers', 'sessions', 'popouts', 'keyboard-shortcuts'],
  },
  {
    id: 'providers',
    title: 'Configure LLM providers',
    summary: 'Settings (齿轮 ⚙) → Providers tab → 选/加 provider → 填 key → Save.',
    body: [
      '在 KodaX Space 里 provider key 走 Settings modal 配 —— 不像 KodaX REPL 改',
      '~/.kodax/config.json,Space 提供 UI:',
      '',
      '1. 点窗口右上齿轮 ⚙ 打开 Settings.',
      '2. 切到 Providers tab,左边列出 13 内建 (Anthropic / OpenAI / Z.ai / OpenRouter /',
      '   Google / DeepSeek / Mistral / Cohere / Together / Groq / Fireworks / Replicate /',
      '   Ollama) + 用户自定义 (+ Add custom).',
      '3. 选 provider → 右边填 API key + 可选 baseURL + 默认 model.',
      '4. Save —— key 优先存系统 keychain (@napi-rs/keyring),不可用时 fall back in-memory (重启丢).',
      '',
      '运行中切 provider: 命令面板 (⌘Shift+P) 搜 "Switch provider",或新建 session 时挑.',
      '/model 命令在 session 内改本 session 模型,/thinking 切 reasoning mode.',
    ].join('\n'),
    aliases: [
      'provider',
      'API key',
      '配置 provider',
      '配 key',
      '配置 API',
      '换模型',
      'change provider',
      '模型设置',
    ],
    nextTopics: ['config', 'sessions', 'commands'],
  },
  {
    id: 'config',
    title: 'Config & data locations',
    summary: 'Space 设置在 ~/.kodax/space/,SDK 共享部分在 ~/.kodax/ (session/skill 跨 REPL).',
    body: [
      'KodaX Space 把数据分两层:',
      '',
      '~/.kodax/ (SDK 共享,KodaX REPL 也写):',
      '  - sessions/   session jsonl + snapshot',
      '  - skills/     用户自定义 skill (skill-creator 写这里)',
      '  - mcp/        MCP server 配置',
      '  - config.json provider key 等共享配置',
      '',
      '~/.kodax/space/ (Space 独占):',
      '  - state.json  UI 状态 (左/右栏宽度 / archived 折叠 / 缩放因子 / 项目排序)',
      '  - logs/       main 进程日志',
      '',
      '大部分 UI 偏好用 Settings modal (⚙) 改 —— 不必手 edit json.',
      '历史版本 ~/.kodax_space 是早期残留目录,启动期会 best-effort 自动清.',
    ].join('\n'),
    aliases: [
      '配置文件',
      '数据目录',
      '存哪',
      'config location',
      'data path',
      '~/.kodax',
      '~/.kodax/space',
    ],
    nextTopics: ['providers', 'sessions', 'troubleshooting'],
  },
  {
    id: 'sessions',
    title: 'Sessions & project sidebar',
    summary: '左侧栏: 项目列表 → 每项目最多展开 8 条 session (溢出走 picker overlay).',
    body: [
      '左侧栏 LeftSidebar 是 Space 的导航中枢:',
      '',
      '- 顶部: 项目列表 (current 置顶,其他按 lastUsedAt desc / 拖排可覆盖).',
      '- 每项目 row 右侧按钮: + New session / Open in OS / Remove.',
      '- 展开项目 → 显示该项目最近 8 条 session;> 8 条点 "+ N more sessions" 弹',
      '  ProjectSessionPicker overlay (居中,fuzzy filter + ↑↓ + Enter 选).',
      '- 项目 row 支持 HTML5 drag-and-drop 拖排 (排序持久化到 state.json).',
      '- 项目支持归档: 右键 contextmenu → Archive,折叠到 "Archived" 区 (折叠状态持久化).',
      '',
      'Session 操作: 选中 session 进对话; 命令面板 (⌘Shift+P) 可 Fork / Rewind /',
      'Rename / Delete (SDK 0.7.42 持久化,跨 REPL 共享).',
    ].join('\n'),
    aliases: ['session', '项目', '会话', '侧栏', 'sidebar', 'project list', '项目列表', '左侧栏'],
    nextTopics: ['quickstart', 'popouts', 'commands'],
  },
  {
    id: 'popouts',
    title: 'Right-side popout panels',
    summary: '右侧栏可弹出 Plan / Diff / Tasks / Terminal / Preview / MCP 6 个独立面板.',
    body: [
      '右侧栏 popout 是 Space 跟 KodaX REPL 最大的形态差: 把对话之外的辅助视图',
      '从对话流分离出来,可独立展开/收起/拖宽.',
      '',
      '6 个内建 popout:',
      '  - Plan       AI 当前 plan_*** 工具产出的计划',
      '  - Diff       write/edit 工具改的文件 inline diff (含 git working-tree fallback)',
      '  - Tasks      todo_*** 工具维护的任务列表',
      '  - Terminal   xterm.js 真 PTY 多 tab (右上 toolbar 终端图标也能开)',
      '  - Preview    任意文件预览 (PDF / docx / xlsx 走 RichPreview,其它 Monaco)',
      '  - MCP        MCP server 状态 + 工具列表',
      '',
      '触发方式: 右上 toolbar 图标手动开 / 命令面板 "Toggle X popout" / Smart popout',
      'director 首次信号自动开. 右栏整体可拖宽 (拖左缘 handle).',
    ].join('\n'),
    aliases: [
      'popout',
      '弹出面板',
      '右侧栏',
      '右栏',
      'right sidebar',
      'plan panel',
      'diff panel',
      'tasks panel',
      '面板',
    ],
    nextTopics: ['smart-popout-director', 'sidebar-resize', 'keyboard-shortcuts'],
  },
  {
    id: 'smart-popout-director',
    title: 'Smart popout director',
    summary: 'session 第一次出现 plan / diff / tasks 信号时,对应 popout 自动展开.',
    body: [
      'KX-I-02 Smart popout director (v0.1.9):',
      '',
      '每 session 第一次出现下列信号时自动展开对应 popout,之后只手动:',
      '  - plan_*** 工具调用      → 自动开 Plan popout',
      '  - write/edit/Multi-Edit  → 自动开 Diff popout',
      '  - todo_*** 工具调用      → 自动开 Tasks popout',
      '',
      '每 session 每类信号只触发一次 (auto-open 标记持久化在 session state),',
      '避免用户手动关掉后又被弹回来.',
      '',
      '不喜欢可在 Settings (⚙) → Preferences tab → 关掉 "Smart popout director".',
    ].join('\n'),
    aliases: ['smart popout', '自动弹出', 'auto popout', 'popout director', 'KX-I-02'],
    nextTopics: ['popouts'],
  },
  {
    id: 'image-paste',
    title: 'Image paste multimodal input',
    summary: 'Ctrl+V 把截图粘到 composer → SDK 自动拼 multimodal content 给 vision 模型.',
    body: [
      'OC-31 图片粘贴多模态输入 (v0.1.9):',
      '',
      '在底部 composer 输入框里直接 Ctrl+V / Cmd+V 粘贴剪贴板里的 PNG / JPEG / WEBP',
      '截图,会在输入框上方显示缩略图 chip.',
      '',
      '送出时 Space 写到 OS temp 目录,把 path 透到 SDK `KodaXContextOptions.inputArtifacts`,',
      'SDK `buildPromptMessageContent` 自动拼成 multimodal content block ({type:"image",',
      'path, mediaType}) 给当前 provider 的 vision 模型 (Claude 3.5+, GPT-4o,',
      'Gemini 1.5+ 等都支持).',
      '',
      '拖拽图片文件到 composer 也行 (同条路径). 选中文件后 X 删除 chip.',
    ].join('\n'),
    aliases: [
      '粘图',
      '粘贴图片',
      '截图',
      'paste image',
      'image input',
      '多模态',
      'multimodal',
      'vision',
      '看图',
    ],
    nextTopics: ['providers', 'quickstart'],
  },
  {
    id: 'commands',
    title: 'Slash commands & command palette',
    summary: '/ 输入框补全 slash / skill; ⌘Shift+P (Ctrl+Shift+P) 全局命令面板.',
    body: [
      'KodaX Space 两套命令入口:',
      '',
      '1. 底部 composer / 补全 — 跟 KodaX REPL 同源:',
      '   - 输 `/` 弹出 popover, 列 slash command + skill (按 name 字典序)',
      '   - skill 和 slash command 都显示为直接 slash 入口: `/<name>`; 重名 skill 显示 `/skill:<name>` 消歧',
      '   - 输 `/<前缀>` 列 slash + skill 都过 prefix; `/skill:<前缀>` 作为旧格式兼容,只列 skill',
      '   - ↑↓ 选, Enter 确认, Esc 关',
      '   - skill-creator 跑完不必重启 Space —— popover 每次 mount 都 forceReload',
      '     SDK skill registry,新生成的 skill 立刻可用',
      '',
      '2. ⌘Shift+P / Ctrl+Shift+P 全局命令面板 (F026, 仿 VS Code):',
      '   - 模糊搜全部 action (切 provider/切 model/Fork/Rewind/Toggle popout 等)',
      '   - 不受当前焦点位置限制',
    ].join('\n'),
    aliases: [
      '命令',
      'slash',
      'command palette',
      '命令面板',
      '/',
      '快捷命令',
      'F26',
      '补全',
    ],
    nextTopics: ['skills', 'keyboard-shortcuts'],
  },
  {
    id: 'skills',
    title: 'Skills in Space',
    summary: 'Skill 在 KodaX SDK 内核统一管 (~/.kodax/skills/); Space 用 `/<name>` 调.',
    body: [
      'Skills 是 KodaX SDK 一级概念 —— Space 不另写 skill 系统,跟 REPL 共享.',
      '',
      '调用: 在 composer 输 `/<name>` 直接触发 skill; 若与 slash command 重名,用 `/skill:<name>` 消歧.',
      '装载位置:',
      '  - ~/.kodax/skills/        用户 skill (skill-creator 写这里)',
      '  - <project>/.kodax/skills/ 项目级 skill (跟仓库走)',
      '',
      '生成新 skill 通常用内建 `skill-creator` skill —— 跟 AI 对话描述需求,它写 skill.md',
      '到 ~/.kodax/skills/<name>/. Space 在 `/` popover 每次 mount 时强制 reload SDK',
      'skill registry,新 skill 立即可见 (不必重启 Space).',
      '',
      'Skill 内部的 system prompt 由 SDK SkillRegistry 注入对话 system message.',
    ].join('\n'),
    aliases: ['skill', '技能', 'skill creator', '生成 skill', '加 skill'],
    nextTopics: ['commands'],
  },
  {
    id: 'sidebar-resize',
    title: 'Resize sidebars & zoom',
    summary: '左/右栏拖中缝改宽 (180–520px); Ctrl+wheel / Ctrl+= / Ctrl+0 全局缩放.',
    body: [
      'Codex parity 视觉 (v0.1.9):',
      '',
      '侧栏拖宽:',
      '  - 左栏右缘 1px 视觉/4px 命中的 ResizeHandle: 拖动改左栏宽',
      '  - 右栏左缘同款 handle: 拖动改右栏宽',
      '  - 双击 reset 默认 (左 260 / 右 320)',
      '  - 拖动期 Esc 取消回起点',
      '  - 范围限制 180–520px,持久化到 state.json',
      '',
      '全局缩放 (Browser-style zoom, Electron webFrame):',
      '  - Ctrl+wheel  增/减 1 step (0.1)',
      '  - Ctrl+= /+   增 1 step',
      '  - Ctrl+-      减 1 step',
      '  - Ctrl+0      reset 到 1.0',
      '  - 范围 [0.5, 3.0],右下角 1.4s 临时 badge 显示当前 factor',
      '  - 持久化 localStorage key "kodax.zoomFactor"',
    ].join('\n'),
    aliases: [
      '缩放',
      'zoom',
      '调字号',
      '改大小',
      '拖栏',
      '拖宽',
      '侧栏宽度',
      'sidebar width',
      'resize',
    ],
    nextTopics: ['keyboard-shortcuts', 'popouts'],
  },
  {
    id: 'keyboard-shortcuts',
    title: 'Keyboard shortcuts',
    summary: 'Quick Ask ⌘K / 命令面板 ⌘Shift+P / 缩放 Ctrl+0/=/- / 全局 Esc 关 modal.',
    body: [
      'KodaX Space 主要快捷键 (Mac 用 ⌘,Win/Linux 用 Ctrl):',
      '',
      '导航:',
      '  ⌘K              Quick Ask 临时问 (一次性 prompt, 不污染 session)',
      '  ⌘Shift+P        命令面板 (模糊搜全部 action)',
      '  Esc             关闭当前 modal / popover / overlay',
      '',
      '编辑 (Mac 必须):',
      '  ⌘C / ⌘V / ⌘X   复制 / 粘贴 / 剪切 (含图片粘到 composer)',
      '  ⌘Z / ⌘Shift+Z  Undo / Redo (Monaco 内有效)',
      '',
      '缩放:',
      '  Ctrl+wheel      增/减 (0.1 step)',
      '  Ctrl+= / Ctrl+- 增/减',
      '  Ctrl+0          reset 1.0',
      '',
      '对话:',
      '  Enter           发送当前消息',
      '  Shift+Enter     换行',
      '  /               触发 slash/skill 补全 popover',
      '  ↑↓              popover 内选项',
    ].join('\n'),
    aliases: [
      '快捷键',
      'shortcut',
      'keybinding',
      '键盘',
      '热键',
      'hotkey',
      'Cmd+K',
      'Ctrl+K',
    ],
    nextTopics: ['commands', 'sidebar-resize'],
  },
  {
    id: 'permissions',
    title: 'Permission prompts',
    summary: '每个写工具走弹窗确认; 三档模式 plan / accept-edits / auto; 多请求批 modal.',
    body: [
      'Space 把 SDK Permission 机制做成弹窗 UI:',
      '',
      '触发: AI 想调写工具 (write / edit / bash / 删文件等) 时,Space 弹 modal',
      '列出文件路径 + 改动摘要,让用户选:',
      '  - Allow once    本次允许',
      '  - Allow always  本 session 全部允许此工具',
      '  - Deny          拒绝',
      '',
      '三档全局 mode (Preferences tab / 命令面板):',
      '  - plan-mode      AI 只能 read + 出 plan,不能 write',
      '  - accept-edits   write/edit 自动 allow,其它仍弹窗 (默认推荐)',
      '  - auto           全部自动 allow (谨慎; 配 KodaX Auto Mode guardrails 用)',
      '',
      'KX-I-05 批量 modal: 多个权限请求同时来时合并成一个 modal 一次确认 (v0.1.8).',
    ].join('\n'),
    aliases: [
      '权限',
      'permission',
      'allow',
      '允许',
      '弹窗',
      'plan mode',
      'accept edits',
      'auto mode',
    ],
    nextTopics: ['commands', 'troubleshooting'],
  },
  {
    id: 'extensions',
    title: 'Extensions and MCP integrations',
    summary: 'Use /extensions for Space MCP status, /extensions sdk for SDK filesystem extension discovery, and explicit opt-in loading for extension runtime.',
    body: [
      'KodaX Space exposes two extension surfaces:',
      '',
      '1. MCP integrations: /extensions or /mcp opens the Space MCP panel and lists configured MCP servers/tools.',
      '2. SDK filesystem extensions: /extensions sdk shows the SDK default extension directory, discovered entrypoints, skipped entries, and active runtime diagnostics.',
      '',
      'SDK extension code is not loaded automatically by default. To load discovered SDK extensions for the current Space process, run /extensions sdk load. To load them automatically before each agent turn, launch Space with KODAX_SPACE_ENABLE_SDK_EXTENSIONS=1.',
      '',
      'The default safe behavior is discovery-only. Loading extensions executes user-installed extension code, so use explicit opt-in for trusted extension directories.',
    ].join('\n'),
    aliases: ['extensions', 'extension', 'plugin', 'plugins', 'sdk extensions', '/extensions', '/mcp', '扩展', '插件'],
    nextTopics: ['commands', 'permissions', 'troubleshooting'],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    summary: '日志 ~/.kodax/space/logs/; 卡死走 Help → Open logs; Reset state 重置 UI.',
    body: [
      'Space 常见排错:',
      '',
      '日志位置:',
      '  - main 进程: ~/.kodax/space/logs/main-YYYY-MM-DD.log',
      '  - renderer: DevTools console (Help 菜单 → Toggle DevTools)',
      '',
      '常见问题:',
      '  - "No provider configured" → ⚙ → Providers tab 配 key',
      '  - "Session not found" 历史 session 报错 → Space 会自动 lazy resume,稍候即可',
      '  - 左栏白屏 → 多半 React hook 顺序回归,看 DevTools console 报 #310;',
      '    回退到上一版 + 上报 issue',
      '  - 历史 session 重启后重弹 "Session done" 通知 → v0.1.10 已修 (从最新 idx 起算)',
      '  - 启动慢/卡 → ~/.kodax/space/state.json 体积过大? 极端情况删它重置 UI 状态',
      '    (不影响 session/skill 数据,那些在 ~/.kodax/)',
      '',
      'Bug 上报: github.com/icetomoyo/KodaX-Space/issues 贴日志 + 复现步骤.',
    ].join('\n'),
    aliases: [
      '问题',
      '排错',
      'troubleshoot',
      'debug',
      '日志',
      'log',
      '报错',
      'error',
      '白屏',
      '卡死',
    ],
    nextTopics: ['config', 'providers'],
  },
  {
    id: 'custom-providers',
    title: 'Custom (self-hosted / OpenAI-compatible) providers',
    summary: '⚙ → Providers → + Add custom —— 填 baseURL + key + model,不用手改 config.json.',
    body: [
      'KodaX Space 用 Settings 表单加自定义 provider(OpenAI-compatible / Anthropic-compatible /',
      '自建网关),不像 KodaX REPL 需要手写 ~/.kodax/config.json:',
      '',
      '1. 点齿轮 ⚙ → Providers tab → 底部 "+ Add custom".',
      '2. 填:名称、API 类型(openai-compat / anthropic-compat)、baseURL、API key、默认 model id.',
      '3. (可选) Reasoning:声明该模型支持的 effort 档位与默认档 —— 决定 /thinking 选择器给',
      '   本 provider 显示哪些档。不支持思考的模型选 "none".',
      '4. Save —— key 存系统 keychain,配置写 ~/.kodax/config.json 的 customProviders(与 KodaX',
      '   共享,所以在 CLI 侧设的字段 Space 编辑时会保留、不覆盖).',
      '',
      '测连接:表单里 "Test connection" 走 SDK verifyProviderCredential 实测一次握手.',
    ].join('\n'),
    aliases: [
      'custom provider',
      '自定义 provider',
      '自建 provider',
      'openai compatible',
      'anthropic compatible',
      'baseURL',
      '自定义模型',
      'self-hosted',
      '本地模型',
    ],
    nextTopics: ['providers', 'config'],
  },
  {
    id: 'tools',
    title: 'Agent tools',
    summary: 'AI 在会话里用一组内建工具(读/搜/编辑/shell/web/artifact);写工具走权限弹窗,Partner 面只读+web+artifact.',
    body: [
      'KodaX Space 的 AI 使用 SDK 内建工具集:',
      '',
      '只读类:read / grep / glob / code_search / repo_overview / symbol / module_context 等 —— 不弹窗.',
      '改动类:write / edit / insert / bash —— 每次调用走 Permission 弹窗(见 permissions 主题).',
      '研究类:web_search / web_fetch —— 只读网络.',
      'Space 自有:create_artifact —— 产出报告/文档/图表到 artifact 面板(不碰项目文件).',
      '',
      'Coder 面:全部工具可用(受权限模式约束).',
      'Partner 面:只放行只读检索 + web 研究 + artifact/KB/source 这类 Space 自有工具;',
      '           不能 write/edit/bash/派生 workflow —— 保证 Partner 是"研究+产出"面而非改代码面.',
    ].join('\n'),
    aliases: ['tools', '工具', 'tool', '能用什么工具', 'agent tools', 'read tool', 'bash tool'],
    nextTopics: ['permissions', 'skills', 'mcp'],
  },
  {
    id: 'mcp',
    title: 'MCP servers',
    summary: '/mcp 或 /extensions 看已配 MCP server; 配置存 ~/.kodax/mcp/ (与 KodaX 共享).',
    body: [
      'KodaX Space 通过 SDK 接 MCP(Model Context Protocol)server,把外部工具/资源接入会话:',
      '',
      '- 查看:命令面板或 /mcp / /extensions 打开 MCP 面板,列出已配 server 与其暴露的工具.',
      '- 配置:MCP server 定义与 KodaX 共享,存 ~/.kodax/mcp/(stdio 或 http transport).',
      '- .mcpb 扩展包:Space 支持导入 .mcpb 打包的 MCP 扩展(见 extensions 主题).',
      '',
      'MCP 工具的副作用类别(只读/改状态/网络)决定它在 Partner 面是否放行:',
      '只读 MCP 工具 Partner 可用,会改状态的 MCP 工具 Partner 阻断.',
    ].join('\n'),
    aliases: ['mcp', 'model context protocol', 'mcp server', '.mcpb', '外部工具', 'integration'],
    nextTopics: ['extensions', 'tools'],
  },
  {
    id: 'repo-intelligence',
    title: 'Repository intelligence',
    summary: '打开项目后 AI 自动建仓库索引(符号/模块/概览),回答"这函数在哪/项目结构"等无需手贴文件.',
    body: [
      'KodaX Space 打开一个项目根后,SDK 的 repo-intelligence 会按需为该仓库建轻量索引:',
      '',
      '- 符号/引用查找、模块上下文、仓库概览等只读能力驱动 AI 的代码理解.',
      '- 索引随打开的项目走(gitRoot = 打开的项目),按需构建 + 缓存,用户无需手动触发.',
      '- Partner 面同样可用这些只读检索能力做代码相关研究.',
      '',
      '这是纯读能力,不改任何文件.',
    ].join('\n'),
    aliases: ['repo intelligence', '仓库智能', '代码索引', 'symbol', '项目结构', 'codebase'],
    nextTopics: ['tools', 'sessions'],
  },
];
